set(CMC_EXAMPLE_BIN_DIR ${CMAKE_INSTALL_BINDIR}/example)
set(CMC_EXAMPLE_LOSSLESS_BIN_DIR ${CMC_EXAMPLE_BIN_DIR}/lossless)

get_filename_component(CMC_EXAMPLE_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt" DIRECTORY)
file(RELATIVE_PATH CMC_EXAMPLE_RELATIVE_DIR "${CMAKE_SOURCE_DIR}" "${CMC_EXAMPLE_SOURCE_DIR}")
set(CMC_EXAMPLE_BUILD_DIR "${CMAKE_BINARY_DIR}/${CMC_EXAMPLE_RELATIVE_DIR}")
set(CMC_EXAMPLE_LOSSLESS_BUILD_DIR ${CMC_EXAMPLE_BUILD_DIR}/lossless)

# Lossless Patch Based Compression example
set(EXAMPLE_LOSSLESS_CMC_PATCH_COMPRESSION cmc_patch_compression)
add_executable(${EXAMPLE_LOSSLESS_CMC_PATCH_COMPRESSION} ${CMAKE_CURRENT_LIST_DIR}/lossless/cmc_patch_compression.cxx)
target_link_libraries(${EXAMPLE_LOSSLESS_CMC_PATCH_COMPRESSION} PUBLIC cmc)
target_include_directories(${EXAMPLE_LOSSLESS_CMC_PATCH_COMPRESSION} PRIVATE ${CMAKE_CURRENT_LIST_DIR})
if(CMC_ENABLE_ALL_WARNINGS)
    target_compile_options(${EXAMPLE_LOSSLESS_CMC_PATCH_COMPRESSION} PRIVATE -Wall -Wextra -Wpedantic)
endif()
set_target_properties(${EXAMPLE_LOSSLESS_CMC_PATCH_COMPRESSION} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMC_EXAMPLE_LOSSLESS_BUILD_DIR}")
install(TARGETS ${EXAMPLE_LOSSLESS_CMC_PATCH_COMPRESSION} DESTINATION ${CMC_EXAMPLE_LOSSLESS_BIN_DIR})
